apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{ .Values.environment }}
  labels:
    app: app
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: app
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000