apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-{{ .Values.Environment }}"
  namespace: "app-{{ .Values.Environment }}"
  labels:
    app: "{{ .Values.Environment }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.Environment }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.Environment }}"
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
