apiVersion: v1
kind: Service
metadata:
  name: "app-{{ .Values.Environment }}"
  namespace: app
spec:
  type: {{ .Values.Service.Type }}
  ports:
    - name: app
      port: {{ .Values.Service.Port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
