apiVersion: v1
kind: Service
metadata:
  name: "app-{{ .Values.Environment }}-service"
  namespace: "{{ .Values.Namespace }}"
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: "app-{{ .Values.Environment }}"
